spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/msaver
    username: postgres
    password: 718293
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
api:
  security:
    token:
      secret: ${JWT_SECRET:7@8#4$5%}