spring:
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/msaver}
    username: ${POSTGRES_DB_USERNAME:postgres}
    password: ${POSTGRES_DB_PASSWORD:718293}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
api:
  security:
    token:
      secret: ${JWT_SECRET:7@8#4$5%}